import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/toaster";

import { cn } from "@/lib/utils";
import AuthProvider from "@/context/AuthProvider";
import StoreProvider from "./StoreProvider";
import Head from "next/head";

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
          <link rel="icon" href="/logo.jpeg" />
        </Head>
      <AuthProvider>
        <StoreProvider>
          <body
            className={cn(
              "min-h-screen bg-background font-sans antialiased",
              fontSans.variable
            )}
          >
            {children}
            <Toaster />
          </body>
        </StoreProvider>
      </AuthProvider>
    </html>
  );
}
